/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_godel_engine_JNI_SeniorCitizenFemaleJNICaller */

#ifndef _Included_com_godel_engine_JNI_SeniorCitizenFemaleJNICaller
#define _Included_com_godel_engine_JNI_SeniorCitizenFemaleJNICaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_godel_engine_JNI_SeniorCitizenFemaleJNICaller
 * Method:    computeTax
 * Signature: (Lcom/godel/dto/TaxDTO;)D
 */
JNIEXPORT jdouble JNICALL Java_com_godel_engine_JNI_SeniorCitizenFemaleJNICaller_computeTax
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
